import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";

import { Toaster, toast } from "sonner";
import "./globals.css";
import AppNav from "@/components/ui/navigation/app-nav";

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={GeistSans.className} suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AppNav/>
          <section className="max-w-7xl mx-auto px-5">
            {children}
          <Toaster position="top-center" richColors closeButton />
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
